### ISSUE TITLE
Compilation fails on CLANG + Linux

### ISSUE THREAD

**Issue by ismail-yilmaz** [anboto/Hdf5#1]
As the title suggests, compilation fails on clang + linux.
A short description can be found [here](https://github.com/ultimatepp/UppHub/pull/29#issuecomment-1872473809).

**Comment by izabala123** [comment]
Hi Ismail

Thank you for reporting this problem.
I have tried to reproduce it unsuccessfully using GCC and CLANG, debug and release. 
Maybe did it appear in a previous version? I have done many improvements the previous days.
Please I would like to ask you to check it again.
My Linux version is Ubuntu 22.04.3 LTS Jammy.

Best regards
Iñaki

**Comment by izabala123** [comment]
Hi Ismail

I have upgraded CLANG until version 17 and I have reproduced your errors. 
They are now fixed, and the changes also work with previous version 14.
My Linux version now is Ubuntu 23.04. Lunar. Kernel version is 5.15.90.4. CLANG version is 17.0.6.
Please update UppHub and check it again. 
Thank you!

Best regards
Iñaki

**Comment by ismail-yilmaz** [comment]
> Hi Ismail
> 
> I have upgraded CLANG until version 17 and I have reproduced your errors. They are now fixed, and the changes also work with previous version 14. My Linux version now is Ubuntu 23.04. Lunar. Kernel version is 5.15.90.4. CLANG version is 17.0.6. Please update UppHub and check it again. Thank you!
> 
> Best regards Iñaki

Hello Iñaki,

I've updated the package via UppHub. CLANG and GCC is at the same version, previous errors are gone but now both compiler fails with the following undeclared identifier error (this is the only one left):

```
upp/.config/u++/theide/UppHub/Hdf5/Hdf5/hdf5.cpp (334): error: use of undeclared identifier 'CopyRowMajor'
upp/.config/u++/theide/UppHub/Hdf5/Hdf5/hdf5.cpp (473): error: use of undeclared identifier 'CopyRowMajor'
```


Best regards,
İsmail

**Comment by ismail-yilmaz** [comment]
Please  disregard the above comment. I forgot to update eigen. :)
Now everthing works just fine.

**Comment by izabala123** [comment]
Perfect, Thank you!
